# Generated by Django 3.2.5 on 2021-07-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('fechadenacimiento', models.DateField()),
                ('tiposangre', models.CharField(max_length=4)),
                ('codigoacceso', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
