# Generated by Django 3.2.5 on 2021-07-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('horariomed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citamedica',
            fields=[
                ('codigocitamed', models.IntegerField(max_length=7, primary_key=True, serialize=False)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('codigodehorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horariomed.horariomed')),
            ],
        ),
    ]
