# Generated by Django 3.2.5 on 2021-07-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superusuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('fechadenacimiento', models.DateField()),
                ('tiposangre', models.CharField(max_length=4)),
                ('contrasena', models.CharField(max_length=40)),
                ('fechadeingreso', models.DateField()),
                ('fechadesalida', models.DateField(null=True)),
                ('licencia', models.CharField(max_length=70)),
                ('sexo', models.CharField(max_length=1)),
                ('estado', models.BooleanField()),
                ('ced_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superusuario.superusuario')),
            ],
        ),
    ]
