# Generated by Django 3.2.5 on 2021-07-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='fechadeingreso',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='fechadesalida',
            field=models.DateField(default='0/0/0'),
        ),
    ]
