# Generated by Django 3.2.5 on 2021-07-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_auto_20210708_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='fechadesalida',
        ),
    ]
