# Generated by Django 3.2.5 on 2021-07-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paramedico', '0001_initial'),
        ('emergencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencionprehospitalari',
            fields=[
                ('idatencion', models.IntegerField(primary_key=True, serialize=False)),
                ('presion', models.IntegerField()),
                ('saturacion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecharegisto', models.DateTimeField(auto_now_add=True)),
                ('ced_paramed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='paramedico.paramedico')),
                ('codigoemergencia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='emergencia.emergencia')),
            ],
        ),
    ]
