# Generated by Django 3.2.5 on 2021-07-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergencia', '0002_alter_emergencia_codigoemergencia'),
        ('paramedico', '0001_initial'),
        ('atencionprehospitalaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencionprehospitalaria',
            fields=[
                ('idatencion', models.AutoField(primary_key=True, serialize=False)),
                ('presion', models.IntegerField()),
                ('saturacion', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('fecharegisto', models.DateTimeField(auto_now_add=True)),
                ('ced_paramed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paramedico.paramedico')),
                ('codigoemergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencia.emergencia')),
            ],
        ),
        migrations.DeleteModel(
            name='Atencionprehospitalari',
        ),
    ]
