# Generated by Django 3.2.5 on 2021-07-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horariomed', '0002_alter_horariomed_codigodehorario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariomed',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
    ]
