# Generated by Django 3.2.5 on 2021-07-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superusuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superusuario',
            name='fechadenacimiento',
            field=models.CharField(max_length=10),
        ),
    ]
