# Generated by Django 3.2.5 on 2021-07-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superusuario', '0001_initial'),
        ('paramedico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramedico',
            name='ced_creador',
            field=models.ForeignKey(default='0000000000', on_delete=django.db.models.deletion.CASCADE, to='superusuario.superusuario'),
        ),
        migrations.AlterField(
            model_name='paramedico',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paramedico',
            name='fechasalida',
            field=models.DateTimeField(default='0/0/0'),
        ),
    ]
