# Generated by Django 3.2.5 on 2021-07-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramedico', '0003_alter_paramedico_fechasalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramedico',
            name='fechasalida',
            field=models.DateTimeField(default='0000-00-00'),
        ),
    ]
