# Generated by Django 3.2.5 on 2021-07-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramedico', '0009_remove_paramedico_fechasalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramedico',
            name='fechaingreso',
            field=models.DateField(auto_now_add=True),
        ),
    ]
