# Generated by Django 3.2.5 on 2021-07-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramedico', '0010_alter_paramedico_fechaingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramedico',
            name='fechasalida',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paramedico',
            name='fechaingreso',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paramedico',
            name='fechanacimiento',
            field=models.CharField(max_length=10),
        ),
    ]
